// ============================================
// COMPREHENSIVE DUMMY DATA FOR BAR POS SYSTEM
// ============================================

export interface Product {
  id: string
  name: string
  category: string
  price: number
  cost: number
  stock: number
  minStock: number
  image: string
  barcode: string
  unit: string
  supplier: string
  isJaba?: boolean
  batchNumber?: string
}

export interface Category {
  id: string
  name: string
  icon: string
  color: string
  productCount: number
}

export interface Transaction {
  id: string
  table: number
  items: { productId: string; name: string; quantity: number; price: number }[]
  subtotal: number
  vat: number
  total: number
  paymentMethod: string
  paymentStatus?: "PAID" | "PENDING" | "PARTIAL" | "FAILED"
  mpesaReceiptNumber?: string | null
  cashAmount?: number | null
  cashBalance?: number | null
  cashier: string
  waiter: string
  timestamp: Date
  status: "completed" | "pending" | "cancelled"
}

export interface Supplier {
  id: string
  name: string
  contact: string
  email: string
  phone: string
  address: string
  category: string
  balance: number
  lastDelivery: Date
  status: "active" | "inactive"
}

export interface StockMovement {
  id: string
  productId: string
  productName: string
  type: "inflow" | "outflow"
  reason: "delivery" | "return" | "sale" | "wastage" | "transfer"
  quantity: number
  previousStock: number
  newStock: number
  supplier?: string
  reference: string
  date: Date
  user: string
}

export interface Staff {
  id: string
  name: string
  role: "admin" | "manager" | "cashier" | "waiter"
  avatar: string
  salesTotal: number
  ordersCount: number
}

export const categories: Category[] = [
  { id: "whiskey", name: "Whiskey", icon: "🥃", color: "#D4A574", productCount: 24 },
  { id: "vodka", name: "Vodka", icon: "🍸", color: "#E8E8E8", productCount: 18 },
  { id: "rum", name: "Rum", icon: "🍹", color: "#C4956A", productCount: 15 },
  { id: "gin", name: "Gin", icon: "🌿", color: "#A8D5BA", productCount: 12 },
  { id: "beer", name: "Beer", icon: "🍺", color: "#F5C842", productCount: 32 },
  { id: "wine", name: "Wine", icon: "🍷", color: "#722F37", productCount: 28 },
  { id: "cocktails", name: "Cocktails", icon: "🍸", color: "#FF6B6B", productCount: 35 },
  { id: "soft-drinks", name: "Soft Drinks", icon: "🥤", color: "#4ECDC4", productCount: 20 },
  { id: "jaba", name: "Jaba", icon: "🌿", color: "#7CB342", productCount: 8 },
]

export const products: Product[] = [
  // Whiskey
  {
    id: "wh001",
    name: "Johnnie Walker Black",
    category: "whiskey",
    price: 850,
    cost: 620,
    stock: 24,
    minStock: 10,
    image: "/johnnie-walker-black-label-whiskey-bottle.jpg",
    barcode: "5000267024202",
    unit: "bottle",
    supplier: "Premium Spirits Ltd",
  },
  {
    id: "wh002",
    name: "Jack Daniels",
    category: "whiskey",
    price: 750,
    cost: 540,
    stock: 18,
    minStock: 8,
    image: "/jack-daniels-tennessee-whiskey-bottle.jpg",
    barcode: "5099873089798",
    unit: "bottle",
    supplier: "Premium Spirits Ltd",
  },
  {
    id: "wh003",
    name: "Jameson Irish",
    category: "whiskey",
    price: 680,
    cost: 480,
    stock: 15,
    minStock: 8,
    image: "/jameson-whiskey-bottle.png",
    barcode: "5011007003005",
    unit: "bottle",
    supplier: "Premium Spirits Ltd",
  },
  {
    id: "wh004",
    name: "Glenfiddich 12yr",
    category: "whiskey",
    price: 1200,
    cost: 880,
    stock: 8,
    minStock: 5,
    image: "/glenfiddich-12-year-scotch-whiskey.jpg",
    barcode: "5010327000176",
    unit: "bottle",
    supplier: "Premium Spirits Ltd",
  },
  {
    id: "wh005",
    name: "Chivas Regal 12yr",
    category: "whiskey",
    price: 950,
    cost: 700,
    stock: 12,
    minStock: 6,
    image: "/chivas-regal-12-year-scotch-whiskey.jpg",
    barcode: "5000299225028",
    unit: "bottle",
    supplier: "Premium Spirits Ltd",
  },

  // Vodka
  {
    id: "vd001",
    name: "Grey Goose",
    category: "vodka",
    price: 920,
    cost: 680,
    stock: 20,
    minStock: 10,
    image: "/grey-goose-vodka-bottle-premium.jpg",
    barcode: "5010677850001",
    unit: "bottle",
    supplier: "Global Beverages",
  },
  {
    id: "vd002",
    name: "Absolut Original",
    category: "vodka",
    price: 580,
    cost: 420,
    stock: 28,
    minStock: 12,
    image: "/absolut-vodka-bottle.jpg",
    barcode: "7312040017010",
    unit: "bottle",
    supplier: "Global Beverages",
  },
  {
    id: "vd003",
    name: "Belvedere",
    category: "vodka",
    price: 1100,
    cost: 820,
    stock: 10,
    minStock: 5,
    image: "/belvedere-vodka-premium-bottle.jpg",
    barcode: "5901041003096",
    unit: "bottle",
    supplier: "Global Beverages",
  },
  {
    id: "vd004",
    name: "Smirnoff Red",
    category: "vodka",
    price: 420,
    cost: 280,
    stock: 35,
    minStock: 15,
    image: "/smirnoff-red-vodka-bottle.jpg",
    barcode: "5410316966001",
    unit: "bottle",
    supplier: "Global Beverages",
  },
  {
    id: "vd005",
    name: "Ciroc",
    category: "vodka",
    price: 980,
    cost: 720,
    stock: 14,
    minStock: 6,
    image: "/ciroc-vodka.png",
    barcode: "0088076174559",
    unit: "bottle",
    supplier: "Global Beverages",
  },

  // Rum
  {
    id: "rm001",
    name: "Bacardi Superior",
    category: "rum",
    price: 520,
    cost: 360,
    stock: 22,
    minStock: 10,
    image: "/bacardi-superior-white-rum.png",
    barcode: "5010677850001",
    unit: "bottle",
    supplier: "Caribbean Imports",
  },
  {
    id: "rm002",
    name: "Captain Morgan",
    category: "rum",
    price: 580,
    cost: 400,
    stock: 18,
    minStock: 8,
    image: "/captain-morgan-spiced-rum-bottle.jpg",
    barcode: "0087000003293",
    unit: "bottle",
    supplier: "Caribbean Imports",
  },
  {
    id: "rm003",
    name: "Havana Club 7yr",
    category: "rum",
    price: 720,
    cost: 520,
    stock: 12,
    minStock: 6,
    image: "/havana-club-7-year-rum-bottle.jpg",
    barcode: "8501110080439",
    unit: "bottle",
    supplier: "Caribbean Imports",
  },
  {
    id: "rm004",
    name: "Appleton Estate",
    category: "rum",
    price: 680,
    cost: 480,
    stock: 15,
    minStock: 6,
    image: "/appleton-estate-jamaica-rum-bottle.jpg",
    barcode: "5024576182700",
    unit: "bottle",
    supplier: "Caribbean Imports",
  },

  // Gin
  {
    id: "gn001",
    name: "Tanqueray",
    category: "gin",
    price: 620,
    cost: 440,
    stock: 16,
    minStock: 8,
    image: "/tanqueray-gin-bottle.jpg",
    barcode: "5000281005393",
    unit: "bottle",
    supplier: "Premium Spirits Ltd",
  },
  {
    id: "gn002",
    name: "Hendricks",
    category: "gin",
    price: 880,
    cost: 650,
    stock: 10,
    minStock: 5,
    image: "/hendricks-gin-bottle.jpg",
    barcode: "5010327705019",
    unit: "bottle",
    supplier: "Premium Spirits Ltd",
  },
  {
    id: "gn003",
    name: "Bombay Sapphire",
    category: "gin",
    price: 680,
    cost: 480,
    stock: 14,
    minStock: 6,
    image: "/bombay-sapphire-gin.png",
    barcode: "5010677714006",
    unit: "bottle",
    supplier: "Premium Spirits Ltd",
  },
  {
    id: "gn004",
    name: "Beefeater",
    category: "gin",
    price: 540,
    cost: 380,
    stock: 20,
    minStock: 10,
    image: "/beefeater-london-dry-gin-bottle.jpg",
    barcode: "5000329002292",
    unit: "bottle",
    supplier: "Premium Spirits Ltd",
  },

  // Beer
  {
    id: "br001",
    name: "Heineken",
    category: "beer",
    price: 120,
    cost: 75,
    stock: 120,
    minStock: 48,
    image: "/heineken-beer-bottle.jpg",
    barcode: "8711000002544",
    unit: "bottle",
    supplier: "Local Distributors",
  },
  {
    id: "br002",
    name: "Corona Extra",
    category: "beer",
    price: 150,
    cost: 95,
    stock: 96,
    minStock: 48,
    image: "/corona-extra-beer-bottle.jpg",
    barcode: "7501064191091",
    unit: "bottle",
    supplier: "Local Distributors",
  },
  {
    id: "br003",
    name: "Budweiser",
    category: "beer",
    price: 110,
    cost: 70,
    stock: 144,
    minStock: 60,
    image: "/budweiser-beer-bottle.jpg",
    barcode: "0018200007248",
    unit: "bottle",
    supplier: "Local Distributors",
  },
  {
    id: "br004",
    name: "Guinness Stout",
    category: "beer",
    price: 180,
    cost: 120,
    stock: 72,
    minStock: 36,
    image: "/guinness-stout-beer-bottle.jpg",
    barcode: "5000213006000",
    unit: "bottle",
    supplier: "Local Distributors",
  },
  {
    id: "br005",
    name: "Stella Artois",
    category: "beer",
    price: 140,
    cost: 90,
    stock: 84,
    minStock: 36,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "5410228142911",
    unit: "bottle",
    supplier: "Local Distributors",
  },

  // Wine
  {
    id: "wn001",
    name: "Moët & Chandon",
    category: "wine",
    price: 2800,
    cost: 2100,
    stock: 12,
    minStock: 4,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "3185370000015",
    unit: "bottle",
    supplier: "Wine Merchants",
  },
  {
    id: "wn002",
    name: "Veuve Clicquot",
    category: "wine",
    price: 3200,
    cost: 2400,
    stock: 8,
    minStock: 3,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "3049614083907",
    unit: "bottle",
    supplier: "Wine Merchants",
  },
  {
    id: "wn003",
    name: "Château Margaux",
    category: "wine",
    price: 4500,
    cost: 3400,
    stock: 6,
    minStock: 2,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "3262155102001",
    unit: "bottle",
    supplier: "Wine Merchants",
  },
  {
    id: "wn004",
    name: "Prosecco DOC",
    category: "wine",
    price: 680,
    cost: 450,
    stock: 24,
    minStock: 10,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "8002750200013",
    unit: "bottle",
    supplier: "Wine Merchants",
  },
  {
    id: "wn005",
    name: "Sauvignon Blanc",
    category: "wine",
    price: 520,
    cost: 340,
    stock: 28,
    minStock: 12,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "9421902960014",
    unit: "bottle",
    supplier: "Wine Merchants",
  },

  // Cocktails (pre-mixed or ingredients)
  {
    id: "ck001",
    name: "Margarita Mix",
    category: "cocktails",
    price: 280,
    cost: 180,
    stock: 30,
    minStock: 12,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "0041331010023",
    unit: "bottle",
    supplier: "Cocktail Supplies Co",
  },
  {
    id: "ck002",
    name: "Mojito Kit",
    category: "cocktails",
    price: 350,
    cost: 220,
    stock: 25,
    minStock: 10,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "0041331010024",
    unit: "kit",
    supplier: "Cocktail Supplies Co",
  },
  {
    id: "ck003",
    name: "Old Fashioned Kit",
    category: "cocktails",
    price: 420,
    cost: 280,
    stock: 18,
    minStock: 8,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "0041331010025",
    unit: "kit",
    supplier: "Cocktail Supplies Co",
  },
  {
    id: "ck004",
    name: "Espresso Martini",
    category: "cocktails",
    price: 380,
    cost: 240,
    stock: 22,
    minStock: 10,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "0041331010026",
    unit: "serving",
    supplier: "Cocktail Supplies Co",
  },

  // Soft Drinks
  {
    id: "sd001",
    name: "Coca-Cola",
    category: "soft-drinks",
    price: 60,
    cost: 35,
    stock: 200,
    minStock: 80,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "5000112548167",
    unit: "bottle",
    supplier: "Local Distributors",
  },
  {
    id: "sd002",
    name: "Red Bull",
    category: "soft-drinks",
    price: 120,
    cost: 80,
    stock: 150,
    minStock: 60,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "9002490100070",
    unit: "can",
    supplier: "Local Distributors",
  },
  {
    id: "sd003",
    name: "Tonic Water",
    category: "soft-drinks",
    price: 80,
    cost: 50,
    stock: 120,
    minStock: 48,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "5000112547078",
    unit: "bottle",
    supplier: "Local Distributors",
  },
  {
    id: "sd004",
    name: "Ginger Beer",
    category: "soft-drinks",
    price: 90,
    cost: 55,
    stock: 100,
    minStock: 40,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "5000112547079",
    unit: "bottle",
    supplier: "Local Distributors",
  },
  {
    id: "sd005",
    name: "Fresh Orange Juice",
    category: "soft-drinks",
    price: 100,
    cost: 65,
    stock: 80,
    minStock: 30,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "5000112547080",
    unit: "bottle",
    supplier: "Local Distributors",
  },

  // Jaba Products (Infused/Special)
  {
    id: "jb001",
    name: "Honey Infused Whiskey",
    category: "jaba",
    price: 950,
    cost: 650,
    stock: 8,
    minStock: 3,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "JABA001001",
    unit: "bottle",
    supplier: "Jaba Artisan Spirits",
    isJaba: true,
    batchNumber: "JB-2024-001",
  },
  {
    id: "jb002",
    name: "Herb Infused Gin",
    category: "jaba",
    price: 880,
    cost: 600,
    stock: 10,
    minStock: 4,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "JABA001002",
    unit: "bottle",
    supplier: "Jaba Artisan Spirits",
    isJaba: true,
    batchNumber: "JB-2024-002",
  },
  {
    id: "jb003",
    name: "Spiced Rum Blend",
    category: "jaba",
    price: 780,
    cost: 520,
    stock: 6,
    minStock: 3,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "JABA001003",
    unit: "bottle",
    supplier: "Jaba Artisan Spirits",
    isJaba: true,
    batchNumber: "JB-2024-003",
  },
  {
    id: "jb004",
    name: "Citrus Vodka Fusion",
    category: "jaba",
    price: 720,
    cost: 480,
    stock: 12,
    minStock: 5,
    image: "/placeholder.svg?height=80&width=80",
    barcode: "JABA001004",
    unit: "bottle",
    supplier: "Jaba Artisan Spirits",
    isJaba: true,
    batchNumber: "JB-2024-004",
  },
]

export const suppliers: Supplier[] = [
  {
    id: "sup001",
    name: "Premium Spirits Ltd",
    contact: "John Smith",
    email: "john@premiumspirits.com",
    phone: "+1 555-0101",
    address: "123 Distillery Lane, New York, NY 10001",
    category: "Spirits",
    balance: 12500,
    lastDelivery: new Date("2024-12-01"),
    status: "active",
  },
  {
    id: "sup002",
    name: "Global Beverages",
    contact: "Sarah Johnson",
    email: "sarah@globalbev.com",
    phone: "+1 555-0102",
    address: "456 Import Ave, Los Angeles, CA 90001",
    category: "Vodka & Spirits",
    balance: 8750,
    lastDelivery: new Date("2024-11-28"),
    status: "active",
  },
  {
    id: "sup003",
    name: "Caribbean Imports",
    contact: "Miguel Rodriguez",
    email: "miguel@caribimports.com",
    phone: "+1 555-0103",
    address: "789 Tropical Blvd, Miami, FL 33101",
    category: "Rum",
    balance: 5200,
    lastDelivery: new Date("2024-11-25"),
    status: "active",
  },
  {
    id: "sup004",
    name: "Wine Merchants",
    contact: "Pierre Dubois",
    email: "pierre@winemerchants.com",
    phone: "+1 555-0104",
    address: "321 Vineyard St, San Francisco, CA 94101",
    category: "Wine & Champagne",
    balance: 28400,
    lastDelivery: new Date("2024-11-30"),
    status: "active",
  },
  {
    id: "sup005",
    name: "Local Distributors",
    contact: "Mike Wilson",
    email: "mike@localdist.com",
    phone: "+1 555-0105",
    address: "654 Warehouse Rd, Chicago, IL 60601",
    category: "Beer & Soft Drinks",
    balance: 3200,
    lastDelivery: new Date("2024-12-02"),
    status: "active",
  },
  {
    id: "sup006",
    name: "Cocktail Supplies Co",
    contact: "Lisa Chen",
    email: "lisa@cocktailsupplies.com",
    phone: "+1 555-0106",
    address: "987 Mixology Way, Las Vegas, NV 89101",
    category: "Cocktail Ingredients",
    balance: 1850,
    lastDelivery: new Date("2024-11-22"),
    status: "active",
  },
  {
    id: "sup007",
    name: "Jaba Artisan Spirits",
    contact: "David Okonkwo",
    email: "david@jabaartisan.com",
    phone: "+1 555-0107",
    address: "147 Craft Circle, Austin, TX 78701",
    category: "Artisan Infusions",
    balance: 4600,
    lastDelivery: new Date("2024-11-29"),
    status: "active",
  },
  {
    id: "sup008",
    name: "Euro Imports Inc",
    contact: "Hans Mueller",
    email: "hans@euroimports.com",
    phone: "+1 555-0108",
    address: "258 Continental Dr, Boston, MA 02101",
    category: "European Spirits",
    balance: 0,
    lastDelivery: new Date("2024-10-15"),
    status: "inactive",
  },
]

export const staff: Staff[] = [
  {
    id: "staff001",
    name: "Marcus Johnson",
    role: "admin",
    avatar: "/placeholder.svg?height=40&width=40",
    salesTotal: 0,
    ordersCount: 0,
  },
  {
    id: "staff002",
    name: "Emily Chen",
    role: "manager",
    avatar: "/placeholder.svg?height=40&width=40",
    salesTotal: 45680,
    ordersCount: 312,
  },
  {
    id: "staff003",
    name: "James Wilson",
    role: "cashier",
    avatar: "/placeholder.svg?height=40&width=40",
    salesTotal: 28450,
    ordersCount: 245,
  },
  {
    id: "staff004",
    name: "Sofia Martinez",
    role: "cashier",
    avatar: "/placeholder.svg?height=40&width=40",
    salesTotal: 32180,
    ordersCount: 278,
  },
  {
    id: "staff005",
    name: "Alex Thompson",
    role: "waiter",
    avatar: "/placeholder.svg?height=40&width=40",
    salesTotal: 18920,
    ordersCount: 156,
  },
  {
    id: "staff006",
    name: "Nina Patel",
    role: "waiter",
    avatar: "/placeholder.svg?height=40&width=40",
    salesTotal: 21450,
    ordersCount: 189,
  },
  {
    id: "staff007",
    name: "Ryan O'Brien",
    role: "waiter",
    avatar: "/placeholder.svg?height=40&width=40",
    salesTotal: 16780,
    ordersCount: 134,
  },
]

export const recentTransactions: Transaction[] = [
  {
    id: "TXN001",
    table: 5,
    items: [
      { productId: "wh001", name: "Johnnie Walker Black", quantity: 2, price: 850 },
      { productId: "br001", name: "Heineken", quantity: 4, price: 120 },
      { productId: "sd003", name: "Tonic Water", quantity: 2, price: 80 },
    ],
    subtotal: 2340,
    vat: 374.4,
    total: 2714.4,
    paymentMethod: "Card",
    cashier: "James Wilson",
    waiter: "Alex Thompson",
    timestamp: new Date("2024-12-02T21:45:00"),
    status: "completed",
  },
  {
    id: "TXN008",
    table: 11,
    items: [
      { productId: "vd001", name: "Grey Goose", quantity: 2, price: 920 },
      { productId: "br002", name: "Corona Extra", quantity: 4, price: 150 },
      { productId: "sd002", name: "Red Bull", quantity: 3, price: 120 },
    ],
    subtotal: 2620,
    vat: 419.2,
    total: 3039.2,
    paymentMethod: "M-Pesa",
    cashier: "Sofia Martinez",
    waiter: "Nina Patel",
    timestamp: new Date("2024-12-02T21:50:00"),
    status: "completed",
  },
  {
    id: "TXN002",
    table: 12,
    items: [
      { productId: "wn001", name: "Moët & Chandon", quantity: 1, price: 2800 },
      { productId: "ck004", name: "Espresso Martini", quantity: 4, price: 380 },
    ],
    subtotal: 4320,
    vat: 691.2,
    total: 5011.2,
    paymentMethod: "Card",
    cashier: "Sofia Martinez",
    waiter: "Nina Patel",
    timestamp: new Date("2024-12-02T21:30:00"),
    status: "completed",
  },
  {
    id: "TXN003",
    table: 8,
    items: [
      { productId: "vd001", name: "Grey Goose", quantity: 1, price: 920 },
      { productId: "sd002", name: "Red Bull", quantity: 6, price: 120 },
    ],
    subtotal: 1640,
    vat: 262.4,
    total: 1902.4,
    paymentMethod: "Cash",
    cashier: "James Wilson",
    waiter: "Ryan O'Brien",
    timestamp: new Date("2024-12-02T21:15:00"),
    status: "completed",
  },
  {
    id: "TXN004",
    table: 3,
    items: [
      { productId: "br002", name: "Corona Extra", quantity: 6, price: 150 },
      { productId: "br003", name: "Budweiser", quantity: 6, price: 110 },
    ],
    subtotal: 1560,
    vat: 249.6,
    total: 1809.6,
    paymentMethod: "Card",
    cashier: "Sofia Martinez",
    waiter: "Alex Thompson",
    timestamp: new Date("2024-12-02T20:58:00"),
    status: "completed",
  },
  {
    id: "TXN005",
    table: 15,
    items: [
      { productId: "gn002", name: "Hendricks", quantity: 1, price: 880 },
      { productId: "sd003", name: "Tonic Water", quantity: 4, price: 80 },
      { productId: "ck002", name: "Mojito Kit", quantity: 2, price: 350 },
    ],
    subtotal: 1900,
    vat: 304.0,
    total: 2204.0,
    paymentMethod: "Card",
    cashier: "James Wilson",
    waiter: "Nina Patel",
    timestamp: new Date("2024-12-02T20:42:00"),
    status: "completed",
  },
  {
    id: "TXN006",
    table: 7,
    items: [
      { productId: "jb001", name: "Honey Infused Whiskey", quantity: 1, price: 950 },
      { productId: "jb002", name: "Herb Infused Gin", quantity: 1, price: 880 },
    ],
    subtotal: 1830,
    vat: 292.8,
    total: 2122.8,
    paymentMethod: "Cash",
    cashier: "Sofia Martinez",
    waiter: "Ryan O'Brien",
    timestamp: new Date("2024-12-02T20:25:00"),
    status: "completed",
  },
  {
    id: "TXN007",
    table: 9,
    items: [
      { productId: "wh001", name: "Johnnie Walker Black", quantity: 1, price: 850 },
      { productId: "br001", name: "Heineken", quantity: 3, price: 120 },
      { productId: "sd001", name: "Coca Cola", quantity: 2, price: 100 },
    ],
    subtotal: 1510,
    vat: 241.6,
    total: 1751.6,
    paymentMethod: "M-Pesa",
    cashier: "James Wilson",
    waiter: "Alex Thompson",
    timestamp: new Date("2024-12-02T20:10:00"),
    status: "completed",
  },
]

export const stockMovements: StockMovement[] = [
  {
    id: "SM001",
    productId: "wh001",
    productName: "Johnnie Walker Black",
    type: "inflow",
    reason: "delivery",
    quantity: 24,
    previousStock: 12,
    newStock: 36,
    supplier: "Premium Spirits Ltd",
    reference: "DEL-2024-0456",
    date: new Date("2024-12-01T09:30:00"),
    user: "Emily Chen",
  },
  {
    id: "SM002",
    productId: "br001",
    productName: "Heineken",
    type: "inflow",
    reason: "delivery",
    quantity: 120,
    previousStock: 48,
    newStock: 168,
    supplier: "Local Distributors",
    reference: "DEL-2024-0457",
    date: new Date("2024-12-01T10:15:00"),
    user: "Emily Chen",
  },
  {
    id: "SM003",
    productId: "vd002",
    productName: "Absolut Original",
    type: "outflow",
    reason: "sale",
    quantity: 3,
    previousStock: 31,
    newStock: 28,
    reference: "TXN-2024-1234",
    date: new Date("2024-12-01T22:30:00"),
    user: "James Wilson",
  },
  {
    id: "SM004",
    productId: "wn001",
    productName: "Moët & Chandon",
    type: "outflow",
    reason: "sale",
    quantity: 2,
    previousStock: 14,
    newStock: 12,
    reference: "TXN-2024-1235",
    date: new Date("2024-12-01T23:15:00"),
    user: "Sofia Martinez",
  },
  {
    id: "SM005",
    productId: "br004",
    productName: "Guinness Stout",
    type: "outflow",
    reason: "wastage",
    quantity: 6,
    previousStock: 78,
    newStock: 72,
    reference: "WST-2024-0089",
    date: new Date("2024-12-02T08:00:00"),
    user: "Emily Chen",
  },
  {
    id: "SM006",
    productId: "jb001",
    productName: "Honey Infused Whiskey",
    type: "inflow",
    reason: "delivery",
    quantity: 12,
    previousStock: 4,
    newStock: 16,
    supplier: "Jaba Artisan Spirits",
    reference: "DEL-2024-0458",
    date: new Date("2024-12-02T11:00:00"),
    user: "Emily Chen",
  },
  {
    id: "SM007",
    productId: "sd002",
    productName: "Red Bull",
    type: "outflow",
    reason: "transfer",
    quantity: 24,
    previousStock: 174,
    newStock: 150,
    reference: "TRF-2024-0034",
    date: new Date("2024-12-02T14:30:00"),
    user: "Marcus Johnson",
  },
  {
    id: "SM008",
    productId: "gn002",
    productName: "Hendricks",
    type: "inflow",
    reason: "return",
    quantity: 2,
    previousStock: 8,
    newStock: 10,
    supplier: "Premium Spirits Ltd",
    reference: "RET-2024-0012",
    date: new Date("2024-12-02T16:00:00"),
    user: "Emily Chen",
  },
]

export const salesData = {
  today: 48520,
  yesterday: 42180,
  thisWeek: 285640,
  lastWeek: 268450,
  thisMonth: 1248650,
  lastMonth: 1156820,
}

export const hourlyStats = [
  { hour: "18:00", sales: 2450, orders: 12 },
  { hour: "19:00", sales: 4820, orders: 24 },
  { hour: "20:00", sales: 8640, orders: 42 },
  { hour: "21:00", sales: 12350, orders: 58 },
  { hour: "22:00", sales: 9870, orders: 48 },
  { hour: "23:00", sales: 6540, orders: 32 },
  { hour: "00:00", sales: 3850, orders: 18 },
]

export const weeklyData = [
  { day: "Mon", sales: 32450, orders: 145 },
  { day: "Tue", sales: 28680, orders: 128 },
  { day: "Wed", sales: 35240, orders: 156 },
  { day: "Thu", sales: 42180, orders: 187 },
  { day: "Fri", sales: 58920, orders: 262 },
  { day: "Sat", sales: 68450, orders: 304 },
  { day: "Sun", sales: 48720, orders: 216 },
]

export const categoryStats = [
  { category: "Whiskey", sales: 28450, percentage: 22 },
  { category: "Beer", sales: 24680, percentage: 19 },
  { category: "Wine", sales: 22340, percentage: 17 },
  { category: "Cocktails", sales: 18920, percentage: 15 },
  { category: "Vodka", sales: 14560, percentage: 11 },
  { category: "Gin", sales: 10240, percentage: 8 },
  { category: "Rum", sales: 6480, percentage: 5 },
  { category: "Other", sales: 3850, percentage: 3 },
]

export const topSellingItems = [
  { id: "wh001", name: "Johnnie Walker Black", sales: 4250, quantity: 28 },
  { id: "br001", name: "Heineken", sales: 3840, quantity: 156 },
  { id: "wn001", name: "Moët & Chandon", sales: 3640, quantity: 8 },
  { id: "vd001", name: "Grey Goose", sales: 2980, quantity: 18 },
  { id: "ck004", name: "Espresso Martini", sales: 2660, quantity: 42 },
]

export const lowStockItems = [
  { id: "wn003", name: "Château Margaux", stock: 6, minStock: 2, status: "warning" },
  { id: "jb003", name: "Spiced Rum Blend", stock: 6, minStock: 3, status: "warning" },
  { id: "jb001", name: "Honey Infused Whiskey", stock: 8, minStock: 3, status: "warning" },
  { id: "wh004", name: "Glenfiddich 12yr", stock: 8, minStock: 5, status: "low" },
  { id: "wn002", name: "Veuve Clicquot", stock: 8, minStock: 3, status: "warning" },
]

export const tables = Array.from({ length: 20 }, (_, i) => ({
  id: i + 1,
  status: i < 3 ? "occupied" : i < 6 ? "reserved" : "available",
  guests: i < 3 ? Math.floor(Math.random() * 6) + 2 : 0,
  waiter: i < 3 ? staff.filter((s) => s.role === "waiter")[i % 3].name : null,
  orderTotal: i < 3 ? Math.floor(Math.random() * 5000) + 1000 : 0,
}))

export const notifications = [
  {
    id: "n1",
    type: "alert",
    title: "Low Stock Alert",
    message: "Château Margaux is running low (6 bottles remaining)",
    time: "5 min ago",
    read: false,
  },
  {
    id: "n2",
    type: "order",
    title: "New Order",
    message: "Table 12 placed a new order - $2,340",
    time: "12 min ago",
    read: false,
  },
  {
    id: "n3",
    type: "delivery",
    title: "Delivery Received",
    message: "Premium Spirits Ltd delivery confirmed - 24 items",
    time: "1 hour ago",
    read: true,
  },
  {
    id: "n4",
    type: "system",
    title: "Daily Report Ready",
    message: "Your daily sales report is ready for review",
    time: "2 hours ago",
    read: true,
  },
  {
    id: "n5",
    type: "alert",
    title: "Price Update",
    message: "Wine Merchants updated prices for 5 products",
    time: "3 hours ago",
    read: true,
  },
]
