import { MenuItem, MenuCategory } from "@/types/menu"

export const menuCategories: MenuCategory[] = [
  { id: "whiskey", name: "Whiskey" },
  { id: "vodka", name: "Vodka" },
  { id: "gin", name: "Gin" },
  { id: "rum", name: "Rum" },
  { id: "brandy", name: "Brandy" },
  { id: "beer", name: "Beer" },
  { id: "wine", name: "Wine" },
  { id: "soft-drinks", name: "Soft Drinks" },
  { id: "energy-drinks", name: "Energy Drinks" },
]

export const menuItems: MenuItem[] = [
  // Whiskey
  {
    id: "wh-001",
    name: "Johnnie Walker Black Label",
    description: "Smooth, smoky finish with notes of vanilla and spice",
    price: 850,
    image: "/johnnie-walker-black-label-whiskey-bottle.jpg",
    category: "whiskey",
    inStock: true,
    tag: "popular",
    isPopular: true,
    brand: "Johnnie Walker",
  },
  {
    id: "wh-002",
    name: "Chivas Regal 12 Year",
    description: "Rich and smooth with honeyed sweetness",
    price: 920,
    image: "/chivas-regal-12-year-scotch-whiskey.jpg",
    category: "whiskey",
    inStock: true,
    tag: "best-seller",
    isPopular: true,
    brand: "Chivas Regal",
  },
  {
    id: "wh-003",
    name: "Glenfiddich 12 Year",
    description: "Elegant single malt with pear and oak notes",
    price: 1100,
    image: "/glenfiddich-12-year-scotch-whiskey.jpg",
    category: "whiskey",
    inStock: true,
    tag: "premium-pick",
    brand: "Glenfiddich",
  },
  {
    id: "wh-004",
    name: "Jack Daniel's",
    description: "Tennessee Whiskey",
    price: 780,
    image: "/jack-daniels-tennessee-whiskey-bottle.jpg",
    category: "whiskey",
    inStock: true,
  },
  {
    id: "wh-005",
    name: "Jameson Irish Whiskey",
    description: "Triple Distilled Irish Whiskey",
    price: 650,
    image: "/jameson-whiskey-bottle.png",
    category: "whiskey",
    inStock: true,
  },
  
  // Vodka
  {
    id: "vk-001",
    name: "Grey Goose",
    description: "Ultra-premium French vodka, crisp and clean",
    price: 1200,
    image: "/grey-goose-vodka-bottle-premium.jpg",
    category: "vodka",
    inStock: true,
    tag: "premium-pick",
    brand: "Grey Goose",
  },
  {
    id: "vk-002",
    name: "Belvedere",
    description: "Premium Polish Vodka",
    price: 1150,
    image: "/belvedere-vodka-premium-bottle.jpg",
    category: "vodka",
    inStock: true,
  },
  {
    id: "vk-003",
    name: "Ciroc",
    description: "French Vodka Made from Grapes",
    price: 1100,
    image: "/ciroc-vodka.png",
    category: "vodka",
    inStock: true,
  },
  {
    id: "vk-004",
    name: "Absolut",
    description: "Swedish Vodka",
    price: 750,
    image: "/absolut-vodka-bottle.jpg",
    category: "vodka",
    inStock: true,
  },
  {
    id: "vk-005",
    name: "Smirnoff Red",
    description: "Classic Russian Vodka",
    price: 550,
    image: "/smirnoff-red-vodka-bottle.jpg",
    category: "vodka",
    inStock: true,
  },
  
  // Gin
  {
    id: "gn-001",
    name: "Bombay Sapphire",
    description: "Premium London Dry Gin",
    price: 850,
    image: "/bombay-sapphire-gin.png",
    category: "gin",
    inStock: true,
  },
  {
    id: "gn-002",
    name: "Tanqueray",
    description: "London Dry Gin",
    price: 800,
    image: "/tanqueray-gin-bottle.jpg",
    category: "gin",
    inStock: true,
  },
  {
    id: "gn-003",
    name: "Beefeater",
    description: "London Dry Gin",
    price: 700,
    image: "/beefeater-london-dry-gin-bottle.jpg",
    category: "gin",
    inStock: true,
  },
  {
    id: "gn-004",
    name: "Hendrick's",
    description: "Scottish Gin with Cucumber & Rose",
    price: 1100,
    image: "/hendricks-gin-bottle.jpg",
    category: "gin",
    inStock: true,
  },
  
  // Rum
  {
    id: "rm-001",
    name: "Captain Morgan Spiced",
    description: "Spiced Rum",
    price: 650,
    image: "/captain-morgan-spiced-rum-bottle.jpg",
    category: "rum",
    inStock: true,
  },
  {
    id: "rm-002",
    name: "Bacardi Superior",
    description: "White Rum",
    price: 600,
    image: "/bacardi-superior-white-rum.png",
    category: "rum",
    inStock: true,
  },
  {
    id: "rm-003",
    name: "Havana Club 7 Year",
    description: "Aged Cuban Rum",
    price: 750,
    image: "/havana-club-7-year-rum-bottle.jpg",
    category: "rum",
    inStock: true,
  },
  {
    id: "rm-004",
    name: "Appleton Estate",
    description: "Jamaican Rum",
    price: 720,
    image: "/appleton-estate-jamaica-rum-bottle.jpg",
    category: "rum",
    inStock: true,
  },
  
  // Brandy
  {
    id: "br-001",
    name: "Hennessy VS",
    description: "Cognac Brandy",
    price: 1300,
    image: "/placeholder.jpg",
    category: "brandy",
    inStock: true,
  },
  {
    id: "br-002",
    name: "Rémy Martin VSOP",
    description: "Premium Cognac",
    price: 1500,
    image: "/placeholder.jpg",
    category: "brandy",
    inStock: true,
  },
  
  // Beer
  {
    id: "be-001",
    name: "Heineken",
    description: "Crisp, refreshing premium lager",
    price: 200,
    image: "/heineken-beer-bottle.jpg",
    category: "beer",
    inStock: true,
    tag: "popular",
    isPopular: true,
    brand: "Heineken",
  },
  {
    id: "be-002",
    name: "Tusker",
    description: "Kenyan Lager",
    price: 180,
    image: "/placeholder.jpg",
    category: "beer",
    inStock: true,
  },
  {
    id: "be-003",
    name: "Guinness",
    description: "Irish Stout",
    price: 220,
    image: "/guinness-stout-beer-bottle.jpg",
    category: "beer",
    inStock: true,
  },
  {
    id: "be-004",
    name: "Corona Extra",
    description: "Mexican Lager",
    price: 250,
    image: "/corona-extra-beer-bottle.jpg",
    category: "beer",
    inStock: true,
  },
  {
    id: "be-005",
    name: "Budweiser",
    description: "American Lager",
    price: 200,
    image: "/budweiser-beer-bottle.jpg",
    category: "beer",
    inStock: true,
  },
  
  // Wine
  {
    id: "wn-001",
    name: "Red Wine - House",
    description: "Premium Red Wine",
    price: 1200,
    image: "/placeholder.jpg",
    category: "wine",
    inStock: true,
  },
  {
    id: "wn-002",
    name: "White Wine - House",
    description: "Premium White Wine",
    price: 1200,
    image: "/placeholder.jpg",
    category: "wine",
    inStock: true,
  },
  {
    id: "wn-003",
    name: "Rosé Wine",
    description: "Premium Rosé",
    price: 1300,
    image: "/placeholder.jpg",
    category: "wine",
    inStock: true,
  },
  
  // Soft Drinks
  {
    id: "sd-001",
    name: "Coca Cola",
    description: "Carbonated Soft Drink",
    price: 100,
    image: "/placeholder.jpg",
    category: "soft-drinks",
    inStock: true,
  },
  {
    id: "sd-002",
    name: "Sprite",
    description: "Lemon-Lime Soda",
    price: 100,
    image: "/placeholder.jpg",
    category: "soft-drinks",
    inStock: true,
  },
  {
    id: "sd-003",
    name: "Fanta Orange",
    description: "Orange Soda",
    price: 100,
    image: "/placeholder.jpg",
    category: "soft-drinks",
    inStock: true,
  },
  {
    id: "sd-004",
    name: "Water - Still",
    description: "Bottled Water",
    price: 80,
    image: "/placeholder.jpg",
    category: "soft-drinks",
    inStock: true,
  },
  
  // Energy Drinks
  {
    id: "ed-001",
    name: "Red Bull",
    description: "Energy Drink",
    price: 200,
    image: "/placeholder.jpg",
    category: "energy-drinks",
    inStock: true,
  },
  {
    id: "ed-002",
    name: "Monster",
    description: "Energy Drink",
    price: 250,
    image: "/placeholder.jpg",
    category: "energy-drinks",
    inStock: true,
  },
]

